# 异常处理

>C++的异常在于语言层面,均为主动抛出,相对而言windows的结构化异常涉及方面要多很多,包括了double free,除零等linux中对应的软中断,这里主要说语言层面的异常(包括MFC)


## boost异常:强大到不说不好
* 可以在任何时刻添加任何类型数据
* 实现异常和数据的分离

 > 也就是说我们可以一层层增加当前层有的信息,是异常诊断更完整

* **boost异常应用处理**

      typedef boost::error_info<struct tag_my_info,string> my_info;

      try{
          //do something with boost::exception
      }
      catch (boost::exception& e){
          e << my_info(some_info);
      }

* *也可以一次性绑定多组信息,如将错误码和错误信息一起(下面将函数名和错误码绑在一起)*

      struct file_open_error : virtual boost::exception { };
      boost::shared_ptr<FILE>  file_open(char const * name, char const * mode)
      {
        if (FILE * f = fopen(name, mode))
          return boost::shared_ptr<FILE>(f, fclose);
        else
          throw file_open_error() <<
            boost::errinfo_file_name(name) <<
            clib_failure("fopen++", errno);
      }

## 使标准抛出时具有boost的能力

      //enable_error_info
      throw enable_error_info(my_err()) << errinfo_errno(101) << errinfo_api_function("fopen");
      //更方便提供位置信息
      BOOST_THROW_EXCEPTION(my_err())



---
* **windows下同时处理MFC异常和标准异常(包括boost)**

      try{
       //...
      }
      //MFC 异常均继承于CEXcep,而且异常都以指针形式抛出,不允许直接delete,需调用成员方法删除
      catch(CException * e)
      {
        TCHAR err[1024] = {0};
        e->GetErrorMessage(err, 1024);
        //do something with err
        e->Delete()
      }
      //boost 异常信息(具体tag一般很深因此使用diagnostic感觉更合理)
      catch (boost::exception& e){
        err = boost::diagnostic_information(e);
      }
      //标准异常均继承于std::excpetion
      catch(std::exception& e)
      {
        std::string err = e.what();
        //do something with err
      }
      catch(...)
      {
        err = "unknown error";
      }


---
## 有关boost异常

>Calling boost::throw_exception does not cause dynamic memory allocations.

What is the cost of BOOST_THROW_EXCEPTION?
>In addition to calling boost::throw_exception, BOOST_THROW_EXCEPTION invokes __FILE__, __LINE__ and the BOOST_THROW_EXCEPTION_CURRENT_FUNCTION macros. The space required to store the information is already included in sizeof(boost::exception).
Calling BOOST_THROW_EXCEPTION does not cause dynamic memory allocations.
